before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: ZiBXr7KpzICbjqOl2SQXOVRUB8PziAwkhwKyRXF7w0neYROUIdYmm8RE7AgpQLoSh1uO3FIfrU/VRoSMImgza+aQAE+2RARsRegqtSLjzNJEE652ObWjRrYxQbPnhJyjgYWO/FqdF/UPFCsQ0ygffHikS9WjYae2FFci1cFim53k2ljK3GmQ9iEI2tRxxrNFxKDeXCTS8yjHjfMutLyywzyOuWAx4QWcI6nNpl5PDx4v+hNZE2Y1g6KBHnwNQnMjrntIcC4KTIuj/gCpOvlODER9t7Qp1a9edahVnkYxTU5BI2JcI9WH3moqBUvIOQcxuMoyS45IStnkzx4gT+V47dpHE7p91aSKCFhjOQ9TNuBppkoMfjRcHi4S8zh0sp/ZFcHr+PxuNADfr32JCiyrTvWj+yNF+W4fAO289VUy0NVN5fEADevqQz8rU1GN0wYK9yeiNGaPqZP6q4HZXSjsFFe2PC4Wh3J3UPgSxY3RWGkTlmSbdOoXxrUiKlipux8V8Jfd2V0I7+NaHg3jAIGApBpM7J9TU/y0W80nmAWJoiq6XHZT4Rcdy6bqwovWbOLF712NXc+urUa7Nd3OEj4PFrt/lo92afq3e0Ex7mapRc7wFoXXU+xal52mbm41wslfacpaZtje8EN/5bID/cfgzxNH3T++u9Pq7P0E5hjJMA4= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
